version: '3.8'

services:
  postgres:
     image: postgres:13
     container_name: postgres
     environment:
      POSTGRES_USER: effiadm
      POSTGRES_PASSWORD: pw123
      POSTGRES_DB: efficlin
     ports:
     - "5432:5432"
     volumes:
     - postgres_data:/var/lib/postgresql/postgres_data


volumes:
    postgres_data:     