version: '3.8'

services:
  postgres:
     image: postgres:13
     container_name: postgres
     environment:
      POSTGRES_USER: effiadm
      POSTGRES_PASSWORD: pw123
      POSTGRES_DB: efficlindb
     ports:
     - "5432:5432"
     volumes:
     - postgres_data:/var/lib/postgresql/postgres_data
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    postgres_data:     